package br.com.totem.impressao;

import android.app.*;
import android.content.*;
import android.os.*;
import org.json.*;

public class PrintService extends Service {
    public static final String CH="totem_print_agent"; private volatile boolean running=true; private PowerManager.WakeLock wake;
    @Override public void onCreate(){ super.onCreate(); createChannel(); startForeground(2206,new Notification.Builder(this,CH).setContentTitle("Totem Impressão").setContentText("Aguardando pedidos da cozinha").setSmallIcon(android.R.drawable.stat_sys_data_bluetooth).build()); PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE); wake=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"Totem:PrintAgent"); wake.acquire(); new Thread(this::loop,"totem-print-loop").start(); }
    private void createChannel(){ if(Build.VERSION.SDK_INT>=26){ NotificationChannel c=new NotificationChannel(CH,"Impressão automática",NotificationManager.IMPORTANCE_LOW); ((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c); } }
    private void loop(){ SharedPreferences p=getSharedPreferences("agent",MODE_PRIVATE); while(running){ try{ String key=p.getString("agent_key",""); String mac=p.getString("printer_mac",""); if(key.isEmpty()||mac.isEmpty()){sleep(2500);continue;} JSONObject req=new JSONObject().put("p_api_key",key); JSONObject r=SupabaseApi.rpc("buscar_impressao_pendente",req); JSONObject pedido=extractPedido(r); if(pedido!=null){ String ticket=toTicket(pedido); boolean ok=true; String err=null; try{Printer.print(this,mac,ticket);}catch(Exception e){ok=false;err=e.getMessage();} JSONObject conf=new JSONObject().put("p_api_key",key).put("p_id",pedido.optString("id")).put("p_ok",ok); if(err==null) conf.put("p_erro",JSONObject.NULL); else conf.put("p_erro",err); try{SupabaseApi.rpc("confirmar_impressao",conf);}catch(Exception ignored){} if(!ok)sleep(5000); else sleep(700); } else sleep(1800); }catch(Exception e){sleep(3500);} } }
    private JSONObject extractPedido(JSONObject r){ if(r==null)return null; Object p=r.opt("pedido"); if(p instanceof JSONObject)return (JSONObject)p; if(r.has("id") && (r.has("itens")||r.has("numero")))return r; Object data=r.opt("data"); if(data instanceof JSONObject){JSONObject d=(JSONObject)data; Object q=d.opt("pedido"); if(q instanceof JSONObject)return (JSONObject)q;} return null; }
    private String toTicket(JSONObject p){ StringBuilder b=new StringBuilder(); b.append("        PEDIDO #").append(p.optString("numero","")).append("\n"); if(p.optBoolean("adicional",false))b.append("   ADICIONAL / NOVOS ITENS\n"); b.append("--------------------------------\n"); String ref=p.optString("referencia",""); if(!ref.isEmpty())b.append("LOCAL: ").append(ref).append("\n"); String cli=p.optString("cliente_nome",""); if(!cli.isEmpty())b.append("CLIENTE: ").append(cli).append("\n"); String gar=p.optString("garcom_nome",""); if(!gar.isEmpty())b.append("GARCOM: ").append(gar).append("\n"); b.append("--------------------------------\n"); JSONArray itens=p.optJSONArray("itens"); if(itens!=null)for(int i=0;i<itens.length();i++){JSONObject x=itens.optJSONObject(i); if(x==null)continue; b.append(x.optInt("quantidade",1)).append("x ").append(x.optString("nome","")).append("\n"); String s=x.optString("sabores","");if(!s.isEmpty())b.append("  ").append(s).append("\n");String o=x.optString("observacao","");if(!o.isEmpty())b.append("  OBS: ").append(o).append("\n");} b.append("--------------------------------\n"); if("aberto".equalsIgnoreCase(p.optString("pagamento_status")))b.append("COMANDA EM ABERTO\n");else b.append(p.optString("forma_pagamento","")).append("\n"); return b.toString(); }
    private void sleep(long ms){try{Thread.sleep(ms);}catch(Exception ignored){}}
    @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;} @Override public void onDestroy(){running=false;if(wake!=null&&wake.isHeld())wake.release();super.onDestroy();} @Override public android.os.IBinder onBind(Intent i){return null;}
}
